### PR TITLE
docs: improve image rendering and various changes

### LINKED ISSUE #715: Use SVG images for icons and allow dark mode properly
As title says. The current landing page logos are not adapted to dark mode and we should be using SVG images

### PR DESCRIPTION
**Pull request by RobPasMue**
Nice SVG color for both dark and light mode
Embed feature branch into the docs-build process
Fix broken links

Closes #715

### CODE REVIEW

**Review by AlejandroFernandezLuces — DISMISSED** [review]
LGTM!

**Review by PipKat — DISMISSED** [review]
Also LGTM.

**Comment by PipKat** [comment]
> Got to solve some issues with SVGs - thanks for approving!

@RobPasMue When Kelly was working on Chris H's team, she wanted us to use SVGs for all images to improve image load times. No one knew of a tool to easily convert PNGs. Nothing was ever done. Just thought you might be interested in this historical tidbit.

**Comment by RobPasMue** [comment]
Yeah I remember that... I think I might have to go with PNGs as well... the main issue is the PDF generation. The docs build fine, but the PDF builds because of this.

**Comment by RobPasMue** [comment]
I'm leaving the SVGs in case we find a solution - but the docs get rendered with the PNG.

**Pull request merged**
