### PR TITLE
chore: Add branch name checker

### PR DESCRIPTION
**Pull request by AlejandroFernandezLuces**
## Description
Add the branch name checker action.

## Issue linked
#1006 

## Checklist
- [x] I have tested my changes locally.
- [x] I have added necessary documentation or updated existing documentation.
- [x] I have followed the coding style guidelines of this project.
- [x] I have added appropriate unit tests.
- [x] I have reviewed my changes before submitting this pull request.
- [x] I have linked the issue or issues that are solved to the PR if any.
- [x] I have assigned this PR to myself.
- [x] I have made sure that the title of my PR follows [Conventional commits style](https://www.conventionalcommits.org/en/v1.0.0/#summary) (e.g. ``feat: extrude circle to cylinder``)

### CODE REVIEW

**Review by RobPasMue — APPROVED** [review]

**Comment by RobPasMue** [comment]
I would also add https://github.com/ansys/actions/blob/main/commit-style/action.yml

**Review by RobPasMue — COMMENTED** [review]
See previous comment

**Review by RobPasMue — CHANGES_REQUESTED** [review]
See previous comment

**Comment by AlejandroFernandezLuces** [comment]
Totally forgot about that action, and I wrote it myself 😄

**Comment by RobPasMue** [comment]
Let's change our "MAINT" refs to "chore" - @AlejandroFernandezLuces 

Do it as part of this PR. You will also have to modify the dependabot.yml file

**Comment by AlejandroFernandezLuces** [comment]
For this PR I'll use the chore tag, but we could add the `maint` tag to the branch name action at some point

**Review by RobPasMue — APPROVED** [review]

**Pull request merged**
