### PR TITLE
feat: re-enable open file on Linux

### LINKED ISSUE #799: Open file broken on Linux service
Open file seems to be broken on Linux service. To be solved on ``test_design_import.py::test_open_file`` (read TODO)

### PR DESCRIPTION
**Pull request by RobPasMue**
Closes #799

### CODE REVIEW

**Comment by RobPasMue** [comment]
Requires server-side resolution - @b-matteo

**Review by RobPasMue — COMMENTED** [review]
Ha... the tests are being skipped. This needs to be solved first.

**Comment by RobPasMue** [comment]
This PR is dependent on https://github.com/ansys/pyansys-geometry/pull/992

**Review by b-matteo — APPROVED** [review]
LGTM. Thank you @RobPasMue

**Pull request merged**
